#!/bin/sh
### BEGIN INIT INFO
# Provides:          thin
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: thin initscript
# Description:       thin
### END INIT INFO

# Original author: Forrest Robertson

# Do NOT "set -e"

DAEMON=/home/ubuntu/.rvm/wrappers/bootup_thin_giv/thin_www_run
SCRIPT_NAME=/etc/init.d/thin_www_giv
CONFIG_PATH=/etc/thin_www_giv

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
  start)
  exec su -l -c "$DAEMON start --all $CONFIG_PATH" ubuntu
  ;;
  stop)
  $DAEMON stop --all $CONFIG_PATH
  ;;
  restart)
  $DAEMON restart --all $CONFIG_PATH
  ;;
  *)
  echo "Usage: $SCRIPT_NAME {start|stop|restart}" >&2
  exit 3
  ;;
esac

:
